// Generated by CoffeeScript 1.7.1
(function() {
  var CORS_PROXY, getJSONWikidataSearchResults, wikidataSearch;

  CORS_PROXY = "http://127.0.0.1:3001/";

  window.availableTags = [];

  window.queries = {};

  $(function() {
    $("#tags").autocomplete({
      source: availableTags,
      select: function(event, ui) {
        console.log(ui.item);
        console.log(ui.item.label);
        $("#item").val(ui.item.label);
        $("#item-id").val(ui.item.id);
        $("#item-description").html(ui.item.desc);
        $("#item-icon").attr("src", "images/" + ui.item.icon);
        return false;
      }
    }).data("ui-autocomplete")._renderItem = function(ul, item) {
      return $("<li>").append("<a>" + item.label + "<br>" + item.desc + "</a>").appendTo(ul);
    };
    return $('#tags').on('keyup', function() {
      var lang, query;
      query = $('#tags').val();
      if (!(query.length < 3 || (queries[query] != null))) {
        lang = $('#language').val();
        console.log("" + lang + ": " + query);
        getJSONWikidataSearchResults(query, lang);
        queries[query] = {};
      }
    });
  });

  wikidataSearch = function(query, language, format) {
    if (language == null) {
      language = "en";
    }
    if (format == null) {
      format = "json";
    }
    return "https://www.wikidata.org/w/api.php?action=wbsearchentities&language=" + language + "&format=" + format + "&search=" + query;
  };

  getJSONWikidataSearchResults = function(query, language, format) {
    $.getJSON(CORS_PROXY + wikidataSearch(query, language, "json"), function(data) {
      if (data.search != null) {
        return data.search.forEach(function(r) {
          if (r.label != null) {
            availableTags.push(r.label);
            queries[query][r.id] = r;
          }
        });
      }
    });
  };

}).call(this);
