// Generated by CoffeeScript 1.7.1
(function() {
  var CORS_PROXY, getJSONWikidataSearchResults, timeoutSetter, wikidataSearch;

  CORS_PROXY = "http://127.0.0.1:3001/";

  window.availableTags = [];

  window.taglist = function() {
    var arr;
    arr = [];
    availableTags.forEach(function(item) {
      return arr.push([item.label, item.desc, item.value]);
    });
    return arr;
  };

  window.queries = {};

  window.lastQuery = "";

  window.lastQueried = "";

  window.lang = "";

  $(function() {
    $("#tags").autocomplete({
      source: availableTags,
      select: function(event, ui) {
        $("#item").val(ui.item.label);
        $("#item-id").val(ui.item.id);
        $("#item-description").html(ui.item.desc);
        $("#item-icon").attr("src", "images/" + ui.item.icon);
        return false;
      }
    }).data("ui-autocomplete")._renderItem = function(ul, item) {
      return $("<li>").append("<a>" + item.label + "<br>" + item.desc + "</a>").appendTo(ul);
    };
    return $('#tags').on('keyup', function() {
      var lang;
      window.lastQuery = $('#tags').val();
      if (!(window.lastQuery.length < 2 || (queries[window.lastQuery] != null) || /^Q[0-9]*$/.test(window.lastQuery) || window.timeout !== null)) {
        lang = $('#language').val();
        getJSONWikidataSearchResults(window.lastQuery, lang);
        queries[window.lastQuery] = {};
        timeoutSetter();
        return window.lastQueried = window.lastQuery;
      }
    });
  });

  window.timeout = null;

  timeoutSetter = function() {
    var f;
    window.timeout = "not null";
    f = function() {
      window.timeout = null;
      if (window.lastQueried !== window.lastQuery) {
        console.log("QUERY SAVER!");
        console.log(window.lastQuery);
        getJSONWikidataSearchResults(window.lastQuery, lang);
        return timeoutSetter();
      }
    };
    return setTimeout(f, 1000);
  };

  wikidataSearch = function(query, language, format) {
    if (language == null) {
      language = "en";
    }
    if (format == null) {
      format = "json";
    }
    return "https://www.wikidata.org/w/api.php?action=wbsearchentities&language=" + language + "&format=" + format + "&search=" + query;
  };

  getJSONWikidataSearchResults = function(query, language) {
    return $.getJSON(CORS_PROXY + wikidataSearch(query, language, "json"), function(data) {
      if (data.search != null) {
        return data.search.forEach(function(result) {
          var formatedResult;
          if (result.label != null) {
            formatedResult = {
              value: result.id,
              label: result.label,
              desc: result.description
            };
            availableTags.push(formatedResult);
            return queries[query][result.id] = result;
          }
        });
      }
    });
  };

}).call(this);
